language: cpp

compiler:
    - gcc

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - make all
    - make unittest

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - g++-5
            - cmake

before_install:
    - export CPPUTEST_VERSION=master
    - export CPPUTEST=cpputest-${CPPUTEST_VERSION}
    - wget https://github.com/cpputest/cpputest/archive/${CPPUTEST_VERSION}.tar.gz
    - tar -xzvf *.tar.gz
    - cd ${CPPUTEST}
    - mkdir _build && cd _build
    - cmake -DC++11=ON -DTESTS=OFF ..
    - make -j4 && sudo make install && cd ../..

